/*
@Author: MaurosMJ
*/
-- Criando varias tabelas
DROP TABLE IF EXISTS PROFISSAO;

CREATE TABLE PROFISSAO (
	IDPROFISSAO INTEGER NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	CONSTRAINT PROFISSAO_IDPROFISSAO_PK PRIMARY KEY (IDPROFISSAO),
	CONSTRAINT PROFISSAO_NOME_UK UNIQUE (NOME)
);

-- Criando uma sequence
DROP SEQUENCE IF EXISTS PROFISSAO_SEQ;

CREATE SEQUENCE PROFISSAO_SEQ START
WITH
	1 INCREMENT BY 1 CACHE 20;

-- Inserindo dados

INSERT INTO
	PROFISSAO
VALUES
	(NEXTVAL('profissao_seq'), 'Estudante');

INSERT INTO
	PROFISSAO
VALUES
	(NEXTVAL('profissao_seq'), 'Engenheiro');

INSERT INTO
	PROFISSAO
VALUES
	(NEXTVAL('profissao_seq'), 'Pedreiro');

INSERT INTO
	PROFISSAO
VALUES
	(NEXTVAL('profissao_seq'), 'Jornalista');

INSERT INTO
	PROFISSAO
VALUES
	(NEXTVAL('profissao_seq'), 'Professor');

COMMIT;

-- Verificando a tabela
SELECT
	*
FROM
	PROFISSAO;

-- Criando uma segunda tabela
DROP TABLE IF EXISTS NACIONALIDADES;

CREATE TABLE NACIONALIDADES (
	IDNACIONALIDADE INTEGER NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	CONSTRAINT NACIONALIDADES_IDNACIONALIDADE_PK PRIMARY KEY (IDNACIONALIDADE),
	CONSTRAINT NACIONALIDADES_NOME_UK UNIQUE (NOME)
);

-- Criando uma sequence
DROP SEQUENCE IF EXISTS NACIONALIDADES_SEQ;

CREATE SEQUENCE NACIONALIDADES_SEQ START
WITH
	1 INCREMENT BY 1 CACHE 20;

INSERT INTO
	NACIONALIDADES
VALUES
	(NEXTVAL('NACIONALIDADES_SEQ'), 'Brasileira');

INSERT INTO
	NACIONALIDADES
VALUES
	(NEXTVAL('NACIONALIDADES_SEQ'), 'Italiana');


INSERT INTO
	NACIONALIDADES
VALUES
	(NEXTVAL('NACIONALIDADES_SEQ'), 'Norte-americana');

INSERT INTO
	NACIONALIDADES
VALUES
	(NEXTVAL('NACIONALIDADES_SEQ'), 'Alemã');


COMMIT;

DROP TABLE IF EXISTS COMPLEMENTO;

CREATE TABLE COMPLEMENTO (
	IDCOMPLEMENTO INTEGER NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	CONSTRAINT COMPLEMENTO_IDCOMPLEMENTO_PK PRIMARY KEY (IDCOMPLEMENTO),
	CONSTRAINT COMPLEMENTO_NOME_UK UNIQUE (NOME)
);

DROP SEQUENCE IF EXISTS COMPLEMENTO_SEQ;

CREATE SEQUENCE COMPLEMENTO_SEQ START
WITH
	1 INCREMENT BY 1 CACHE 20;

INSERT INTO
	COMPLEMENTO
VALUES
	(NEXTVAL('COMPLEMENTO_SEQ'), 'Casa');

INSERT INTO
	COMPLEMENTO
VALUES
	(NEXTVAL('COMPLEMENTO_SEQ'), 'Apartamento');

COMMIT;

--Verificando dados:
SELECT
	*
FROM
	COMPLEMENTO;

DROP TABLE IF EXISTS BAIRRO;

CREATE TABLE BAIRRO (
	IDBAIRRO INTEGER NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	CONSTRAINT BAIRRO_IDBAIRRO_PK PRIMARY KEY (IDBAIRRO),
	CONSTRAINT BAIRRO_NOME_UK UNIQUE (IDBAIRRO)
);

DROP SEQUENCE IF EXISTS BAIRRO_SEQ;

CREATE SEQUENCE BAIRRO_SEQ START
WITH
	1 INCREMENT BY 1 CACHE 20;

INSERT INTO
	BAIRRO
VALUES
	(NEXTVAL('bairro_seq'), 'Cidade Nova');

INSERT INTO
	BAIRRO
VALUES
	(NEXTVAL('bairro_seq'), 'Centro');

INSERT INTO
	BAIRRO
VALUES
	(NEXTVAL('bairro_seq'), 'São Pedro');

INSERT INTO
	BAIRRO
VALUES
	(NEXTVAL('bairro_seq'), 'Santa Rosa');

COMMIT;

-- Verificando dados
SELECT
	*
FROM
	BAIRRO;